### ISSUE TITLE
}bedrock.cube.data.copy won't copy strings on consolidated levels - pSuppressConsol parameter is missing

### ISSUE THREAD

**Issue by pbuncik** [cubewise-code/bedrock#41]
**Describe the bug**
The process is supposed to copy values intra-cube. This should apply for String values and depending on `pSuppressConsol` parameter it should be possible to choose the consolidated levels to be included in the copy.
The `pSuppressConsol` parameter is missing in the process. There is certain logic implemented in the process that sets internal variable `sSuppressConsol` to 0 only in case when mapping between elements is applied on C level element. Hence there is no way how to instruct the process to not skip consolidated elements if needed for example when copying Strings.

**To Reproduce**
1. Run the process with pCube set to an }ElementAttributes cube, set mapping to copy any string attribute to another one. Make sure that the base dimension contains consolidated elements.
2. Check which element attribute values were copied - consolidated elements were skipped.

**Expected behavior**
The process should be consistent with B3 in terms of its results - thus pSuppressConsol parameter should be implemented.

**Screenshots**
NA

**Version**
 - OS: Windows Server 2012 R2
  - TM1 Server Version: PAL 2.0.6.

**Additional context**
NA

**Comment by lotsaram** [comment]
fixed in #73

**Comment by raeldor** [comment]
I still can't get this to work when the string measure is a calculated measure.
